### ISSUE TITLE
Header Multilingual link wrong 

### ISSUE THREAD

**Issue by Mayavi345** [themefisher/airspace-hugo#112]
Hello, I am trying to build a multilingual site (I didn't change the file).  When I generate the page on the local side, the Header Multilingual link is wrong , it is Navigate to another files.
However I changed other template with multilingual , it is OK.

 Ex Generated file :  exampleSite ->public -> about ->index.html
   
 code:
>                  <select id="select-language" onchange="location = this.value;">
>                   <option id="en" value="http://examplesite.org/author/john-doe/" selected>  En
>                   </option>
>                   <option id="fr" value="http://examplesite.org/fr/author/john-doe/">Fr
>                   </option>
>                 </select>

Many thanks ,

**Comment by dav1dwa** [comment]
Hi @Mayavi345 , I also came across this problem. This seems to be caused by the `partialCached` function, which has been added with 3648fcc in `layouts/_default/baseof.html`. I reverted it to `partial` and the language select works fine again. I also reverted to `partial` to load the footer since the cache broke the google maps feature on the contact page.

**Comment by somratpro** [comment]
Hello All,

Thanks for your concern, I removed the cached for the header. now the problem has been resolved. 

Also if you like this template, a star to the repository would be incredible.
