### ISSUE TITLE
Pages such as about, project, service disappear after deploying.

### ISSUE THREAD

**Issue by Mosesdejaviano** [themefisher/airspace-hugo#199]
Once the pages such as about, project, and service are edited and updated, it keeps not showing on the main page after deploying. Thanks.

**Comment by somratpro** [comment]
Hello @Mosesdejaviano 

Thanks for choosing our template. I did not get your issue properly, because I didn't see any disappear on my local machine. Are you using forestry or a local machine? Can you please pull the latest code and check it again? If this keeps happening, I'll prefer a screen record to understand your issue. Thank you

**Comment by Mosesdejaviano** [comment]
Thanks for your reply. I used forestry. I noticed that after I finish editing on forestry, all the layout disappeared. So I need to use my local machine, and it worked fine. I think the issue is with forestry. Thanks once again

**Comment by mehedi-sharif** [comment]
@Mosesdejaviano 
Good to know that your problem has been solved. We recommend you put a star in this repo. And the future if you build something with our theme you can showcase your site in this repository to inspire others from here https://github.com/themefisher/airspace-hugo/discussions/196 . 
Thanks for creating with us
